name: Auto Deploy to ACE Cloud

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH key and connectivity
        run: |
          echo "Private key has $(wc -l < ~/.ssh/id_rsa) lines"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -vvv \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            echo SSH_OK || echo SSH_FAILED

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Build (if needed)
        run: |
          npm ci
          npm run build

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" \
            ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/


